{
 "title": "Blacklist Manager",
 "time": { "from": "2022-09-09T06:58:26.873Z", "to": "2022-09-09T08:58:26.873Z" },
 "panels": [
  {
   "title": "Court orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(blacklist_manager_failed_court_orders[1m])",
     "legendFormat": "Failed court orders"
    },
    {
     "expr": "increase(blacklist_manager_processed_court_orders[1m])",
     "legendFormat": "Processed court orders"
    }
   ]
  },
  {
   "title": "Consensus activations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(blacklist_manager_failed_consensus_activations[1m])",
     "legendFormat": "Failed consensus activation"
    },
    {
     "expr": "increase(blacklist_manager_processed_consensus_activations[1m])",
     "legendFormat": "Processed consensus activation"
    }
   ]
  },
  {
   "title": "Confiscation transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(blacklist_manager_submitted_transactions[$__rate_interval])",
     "legendFormat": "Submitted transactions"
    },
    {
     "expr": "increase(blacklist_manager_rejected_transactions[1m])",
     "legendFormat": "rejected transactions"
    }
   ]
  },
  {
   "title": "Funds propagation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(blacklist_manager_successfully_propagated_funds[1m])",
     "legendFormat": "Propagated funds"
    },
    {
     "expr": "increase(blacklist_manager_failed_node_propagation[1m])",
     "legendFormat": "Failed nodes"
    }
   ]
  },
  { "title": "Blacklist Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } }
 ]
}